Use ControlModule for getting the move direction
MrChickenRocket/chickynoid pull request #1
Opened 2021-12-30 01:13 UTC by tacheometry

This change allows for controller, mobile, keyboard, etc support. Directions are also analogue now, so move vectors such as "diagonally to the left" can be inputted.

2021-12-30 01:13 UTC, tacheometry commented
One caveat is that some users might have forked the core scripts, and this method might not be available to them if these modules are deleted.

2021-12-30 01:20 UTC, grilme99 requested changes
This should ideally fall back to the original method if the ControlModule is unavailable. It would also be cleaner if getting the move vector is put into its own method.

2021-12-30 01:23 UTC, OverHash commented on src/Client/init.lua
> +        moveVector = moveVector.Unit
Doesn't `ControlModule:GetMoveVector()` already return a unit vector?

2021-12-30 01:29 UTC, tacheometry commented on src/Client/init.lua
> +        moveVector = moveVector.Unit
Nope - try printing it while holding W and D for example.

2021-12-31 02:19 UTC, grilme99 commented
Closing this because the changes were worked in with the client refactor, but I had no good way of merging this in via Git.

2021-12-31 02:19 UTC, closed without merging